//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMG_Soft_MailSender.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMG_Soft_MailSender.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1308978920_001_01 {
            get {
                object obj = ResourceManager.GetObject("1308978920_001_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308979161_disk {
            get {
                object obj = ResourceManager.GetObject("1308979161_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308980425_001_06 {
            get {
                object obj = ResourceManager.GetObject("1308980425_001_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308980468_001_39 {
            get {
                object obj = ResourceManager.GetObject("1308980468_001_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308984940_document_import {
            get {
                object obj = ResourceManager.GetObject("1308984940_document_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308985619_page_white_excel {
            get {
                object obj = ResourceManager.GetObject("1308985619_page_white_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308986180_Microsoft_Office_2007_Excel {
            get {
                object obj = ResourceManager.GetObject("1308986180_Microsoft Office 2007 Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308986224_Arzo_Icons_Icon_96_2 {
            get {
                object obj = ResourceManager.GetObject("1308986224_Arzo Icons Icon 96 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1308986488_folder_horizontal_open {
            get {
                object obj = ResourceManager.GetObject("1308986488_folder_horizontal_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309075161_article_48 {
            get {
                object obj = ResourceManager.GetObject("1309075161_article 48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309075264_send_group {
            get {
                object obj = ResourceManager.GetObject("1309075264_send-group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309075310_address_book {
            get {
                object obj = ResourceManager.GetObject("1309075310_address-book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309075338_edit_notes {
            get {
                object obj = ResourceManager.GetObject("1309075338_edit-notes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309075416_download {
            get {
                object obj = ResourceManager.GetObject("1309075416_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309084894_Flag2LeftRed {
            get {
                object obj = ResourceManager.GetObject("1309084894_Flag2LeftRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309167211_mark_as_read_16 {
            get {
                object obj = ResourceManager.GetObject("1309167211_mark_as_read_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309236473_Close {
            get {
                object obj = ResourceManager.GetObject("1309236473_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309236539_cross {
            get {
                object obj = ResourceManager.GetObject("1309236539_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309237517_netvibes {
            get {
                object obj = ResourceManager.GetObject("1309237517_netvibes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309238852_Previous {
            get {
                object obj = ResourceManager.GetObject("1309238852_Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309238988_Next {
            get {
                object obj = ResourceManager.GetObject("1309238988_Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309239079_Previous {
            get {
                object obj = ResourceManager.GetObject("1309239079_Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309239079_Previous1 {
            get {
                object obj = ResourceManager.GetObject("1309239079_Previous1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309240189_info_blog {
            get {
                object obj = ResourceManager.GetObject("1309240189_info-blog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309240663_Globe {
            get {
                object obj = ResourceManager.GetObject("1309240663_Globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309240987_kpackage {
            get {
                object obj = ResourceManager.GetObject("1309240987_kpackage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309241033_kpackage {
            get {
                object obj = ResourceManager.GetObject("1309241033_kpackage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1309667678_text_enriched {
            get {
                object obj = ResourceManager.GetObject("1309667678_text-enriched", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blocked {
            get {
                object obj = ResourceManager.GetObject("Blocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section we prepare the content of email
        ///
        ///to insert new content click new button and enter content profile name for example Ad-01
        ///
        ///then enter subject of email
        ///and enter email body
        ///
        ///if you email format is html check then html format check box
        ///
        ///for finish click save button.
        /// </summary>
        internal static string CONTENT_ENGLISH {
            get {
                return ResourceManager.GetString("CONTENT_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در اين بخش  محتواي ايميل ارسالي را آماده ميکنيم
        ///
        ///براي ثبت يک محتواي ايميل دکمه جديد را بزنيد و نام پروفايل را وارد نماييد مثلا ايميل تبليغاتي شماره 1
        ///
        ///سپس در قسمت موضوع، موضوع ايميل را وارد نماييد
        ///
        ///متن ايميل را نيز وارد نماييد
        ///
        ///در صورتيکه متن ايميل شما بصورت html است گزينه فرمت html را تيک بزنيد
        ///
        ///درپايان دکمه ذخيره را بزنيد.
        /// </summary>
        internal static string CONTENT_PERSIAN {
            get {
                return ResourceManager.GetString("CONTENT_PERSIAN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Error_send {
            get {
                object obj = ResourceManager.GetObject("Error_send", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_new {
            get {
                object obj = ResourceManager.GetObject("mail_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_send {
            get {
                object obj = ResourceManager.GetObject("mail_send", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient E-mail 
        ///Click the new button to insert a new profile and enter the recipient&apos;s e-mail 
        ///
        ///To enter the mailing list you can use the following methods: 
        ///
        ///Manual method: 
        ///Click inser new mail and enter email address
        ///
        ///The Excel file:
        ///Click import excel button to show import excel file wizard
        ///
        ///The Text file:
        ///You can also enter the mailing list from a text file,
        ///click import text button to show import text form
        ///
        ///Delete e-mail:
        ///To remove one or more e-mail select  them and click delete ema [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RECEIPIENTS_ENGLISH {
            get {
                return ResourceManager.GetString("RECEIPIENTS_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گيرنده ايميل
        ///ليست گيرنده هاي ايميل را در اين بخش وارد  ميکنيم
        ///براي شروع دکمه جديد را بزنيد و نام پروفايل گيرنده ايميل را وارد نماييد
        ///
        ///براي وارد کردن ليست ايميل ميتوانيد از سه روش زير استفاده نماييد:
        ///
        ///روش دستي:
        ///دکمه ثبت ايميل جديد را بزنيد و  ايميل را وارد نماييد
        ///
        ///روش فايل اکسل:
        ///شما ميتوانيد ليست ايميل ها را از يک فايل اکسل به برنامه وارد نماييد براي اينکار دکمه اکسل را بزنيد تا فرم استخراج ايميل از فايل اکسل نشان  داده شود 
        ///
        ///
        ///روش فايل متني:
        ///شما ميتوانيد ليست ايميل ها را از يک فايل متني نيز وار [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RECEIPIENTS_PERSIAN {
            get {
                return ResourceManager.GetString("RECEIPIENTS_PERSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender of email
        ///
        ///Method 1: Public email providers such as yahoo,gmail
        ///
        ///click new button and enter name of profile for example sample@gmail.com
        ///
        ///in display name enter the name that want to display in sender of email in user email
        ///in replay email,enter email that you want to user replay whit
        ///check Request a delivery if you want disposition notification
        ///check Use SSL connection
        ///
        ///enetr email server for example server of gmail is smpt.gmail.com 
        ///enter email as user name
        ///enter email password
        ///
        ///enter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SENDER_ENGLISH {
            get {
                return ResourceManager.GetString("SENDER_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرستنده ايميل
        ///براي شروع ميبايست ابتدا ايميل فرستنده را تنظيم نماييد
        ///روش اول:استفاده از ايميل هاي مجاني مثل گوگل
        ///براي اينکار ابتدا دکمه جديد را بزنيد ويک نام در پنجره اي که نشان دا ده ميشود وارد نماييد و دکمه قبول را بزنيد
        /// در قسمت  از آدرس، ايميل فرستنده را وارد نماييد مثلا  sample@gmail.com
        ///
        ///درقسمت نام نمايشي ، نامي که ميخواهيد در قسمت فرستنده ايميل نشان داده شود را وارد نماييد
        ///
        ///در قسمت ايميل پاسخ، ايميلي که ميخواهيد گيرنده ايميل براي پاسخ استفاده کند را وارد نماييد
        ///
        ///درخواست رسيد از سرور جهت تايي [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SENDER_PERSIAN {
            get {
                return ResourceManager.GetString("SENDER_PERSIAN", resourceCulture);
            }
        }
    }
}
